spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mall?useSSL=false&allowPublicKeyRetrieval=true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:db/mapper/*.xml